### ISSUE TITLE
Test Failed JIT/SIMD/VectorMatrix_ro/VectorMatrix_ro.sh

### ISSUE THREAD

**Issue by sherlock-xu** [heixixia/07-13failed-test#2]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20220710.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1870905&view=ms.vss-test-web.build-test-results-tab&runId=49025330&resultId=103742&paneView=debug)

Failed test:
```
coreclr Linux arm Checked gcstress0xc @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/SIMD/VectorMatrix_ro/VectorMatrix_ro.sh


```

**Error message:**
```
/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_ro/VectorMatrix_ro.sh: line 386:   236 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorMatrix_ro/VectorMatrix_ro.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorMatrix_ro.dll ''
[createdump] Gathering state for process 236 corerun
[createdump] Crashing thread 000000ec signal 0000000b
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.236.dmp
[createdump] Written 51298304 bytes (12524 pages) to core file
[createdump] Dump successfully written
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_ro/VectorMatrix_ro.sh
Expected: True
Actual:   False


Stack trace
   at JIT_SIMD._VectorMatrix_ro_VectorMatrix_ro_._VectorMatrix_ro_VectorMatrix_ro_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by VincentBu** [comment]
add label: blocking-clean-ci-optional、GCStress
