### ISSUE TITLE
Test Failed tracing/eventpipe/processenvironment/processenvironment/processenvironment.sh

### ISSUE THREAD

**Issue by sherlock-xu** [heixixia/07-13failed-test#4]
Run: [runtime-coreclr r2r-extra 20220710.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1871413&view=ms.vss-test-web.build-test-results-tab&runId=49032984&resultId=108641&paneView=debug)

Failed test:
```
R2R Linux arm Checked gcstress0xc @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- tracing/eventpipe/processenvironment/processenvironment/processenvironment.sh
- JIT/SIMD/VectorMatrix_r/VectorMatrix_r.sh



```

**Error message:**
```
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/processenvironment.sh: line 275: -r:/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/IL-CG2/*.dll: No such file or directory
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/processenvironment.sh: line 408: 17679 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/processenvironment/processenvironment/processenvironment.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/IL-CG2/common.dll
07:01:06
Response file: /root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/common.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/IL-CG2/common.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/common.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/common.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/common.dll
07:01:11
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
07:01:11
Response file: /root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/Microsoft.Diagnostics.NETCore.Client.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/Microsoft.Diagnostics.NETCore.Client.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/Microsoft.Diagnostics.NETCore.Client.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/Microsoft.Diagnostics.NETCore.Client.dll
07:01:18
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/IL-CG2/processenvironment.dll
07:01:18
Response file: /root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/processenvironment.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/IL-CG2/processenvironment.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/processenvironment.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/processenvironment.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/processenvironment.dll
07:01:22
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false processenvironment.dll ''
0.0s: running sub-process: /root/helix/work/correlation/corerun /root/helix/work/workitem/e/tracing/eventpipe/processenvironment/processenvironment/processenvironment.dl


Stack trace
   at tracing_eventpipe._processenvironment_processenvironment_processenvironment_._processenvironment_processenvironment_processenvironment_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/VectorMatrix_r.sh: line 253: -r:/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/IL-CG2/*.dll: No such file or directory
/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/VectorMatrix_r.sh: line 386:   741 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorMatrix_r/VectorMatrix_r.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/IL-CG2/VectorMatrix_r.dll
06:45:36
Response file: /root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/VectorMatrix_r.dll.rsp
/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/IL-CG2/VectorMatrix_r.dll
-o:/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/VectorMatrix_r.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/VectorMatrix_r.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/VectorMatrix_r.dll
06:45:41
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorMatrix_r.dll ''
[createdump] Gathering state for process 741 corerun
[createdump] Crashing thread 000002e5 signal 0000000b
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.741.dmp
[createdump] Written 51273728 bytes (12518 pages) to core file
[createdump] Dump successfully written
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/SIMD/VectorMatrix_r/VectorMatrix_r.sh
Expected: True
Actual:   False


Stack trace
   at JIT_SIMD._VectorMatrix_r_VectorMatrix_r_._VectorMatrix_r_VectorMatrix_r_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by VincentBu** [comment]
add label: blocking-clean-ci-optional、GCStress
