### ISSUE TITLE
Test failure System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

### ISSUE THREAD

**Issue by sherlock-xu** [heixixia/07-13failed-test#8]
Run: [runtime-libraries-coreclr outerloop 20220714.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1880437&view=ms.vss-test-web.build-test-results-tab&runId=49187402&resultId=104088&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout


```

**Error message:**
```
Assert.Equal() Failure
Expected: ConnectionAborted
Actual:   ConnectionIdle


Stack trace
   at System.Net.Quic.Tests.QuicTestBase.AssertThrowsQuicExceptionAsync(QuicError expectedError, Func`1 testCode) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 53
   at System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 584
--- End of stack trace from previous location ---
```

**Comment by sherlock-xu** [comment]
Failed again in:[runtime-libraries-coreclr outerloop 20220714.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1880437&view=ms.vss-test-web.build-test-results-tab&runId=49187408&resultId=101921&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open

- System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: True)

```

**Error message:**
```
System.ComponentModel.Win32Exception : An error occurred trying to start process 'notepad.exe' with working directory 'C:\h\w\BA3D09D8\w\B95D09DA\e'. Access is denied.


Stack trace
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs:line 98
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs:line 25
   at System.Diagnostics.Process.Start() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1282
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1359
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1317
   at InvokeStub_ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
